### ISSUE TITLE
Use GithubActions instead of Travis

### ISSUE THREAD

**Issue by OskarStark** [exozet/docker-php-fpm#159]
### Todos

* [x] GithubActions for `release/7.4` #158 
* [x] GithubActions for `release/7.3` #160 & #164
* [x] GithubActions for `release/7.2` #161 & #163
* [x] GithubActions for `release/7.1` #162
* [x] GithubActions for `release/7.0` #165
* [x] GithubActions for `release/5.6` #166
* [x] GithubActions for `release/5.5` #167
* [x] GithubActions for `release/5.4` #168
* [x] Update README and use GithubAction Status badge instead of Travis-Badge - @OskarStark 
* [x] Disable Travis-Webhook when all are switched to GitubActions - @DracoBlue 
![Bildschirmfoto 2020-10-23 um 11 42 03](https://user-images.githubusercontent.com/35926/96988584-cd29b280-1524-11eb-82be-6f2d928860b3.png)

**Comment by DracoBlue** [comment]
lgtm!

thanks for the work on this matter!
